[phases.setup]
nixPkgs = ["nodejs_18", "npm", "chromium"]

[phases.install]
# Skip Chromium download - use system chromium
cmds = [
    "npm ci --production",
    "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true"
]

[phases.build]
# No build phase needed - we're serving directly
dependsOn = ["install"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*/bin/chromium"
