[phases.setup]
aptPkgs = [
  "wget",
  "gnupg", 
  "ca-certificates",
  # Required libraries for Puppeteer's bundled Chromium (Ubuntu 24.04 compatible)
  "libglib2.0-0",
  "libnss3",
  "libatk-bridge2.0-0", 
  "libdrm2",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libxss1",
  "libasound2t64",
  "libatspi2.0-0",
  "libgtk-3-0"
]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "rm -f package-lock.json",
  "npm install --production=false"
]

[phases.build]
cmds = [
  "npm prune --production"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
# Let Puppeteer use its bundled Chromium
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
