[phases.setup]
nixPkgs = ["nodejs_18", "chromium"]

[phases.install]
cmds = ["npm ci --production"]

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"