[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "${{ RAILWAY_PORT }}"

[healthcheck]
path = "/health"
timeout = 30
interval = 60